DocBlog/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import index

urlpatterns = [
    path("admin/", admin.site.urls),
    path('blog/', include("blog.urls")),
    path('posts/', include("posts.urls")),
    path('', index, name="index")
]

blog/urls.py
from django.urls import path
from .views import blog, index

urlpatterns = [
    path('', index, name="blog-index"),
    path('blog-<str:numero_blog>/', blog, name="blog-article"),
]

posts/urls.py
from django.urls import path
from posts.views import BlogHome, BlogPostCreate, BlogPostEdit,BlogPostDetail,BlogPostDelete


app_name = "posts"

urlpatterns = [
    path('', BlogHome.as_view(), name="home"),
    path('create/', BlogPostCreate.as_view(), name="create"),
    path('edit/<str:slug>/', BlogPostEdit.as_view(), name="edit"),
    path('<str:slug>/', BlogPostDetail.as_view(), name="post"),
    path('delete/<str:slug>/', BlogPostDelete.as_view(), name="delete"),
]

blog/models.py
from django.db import models

# Create your models here.

posts/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse
from django.template.defaultfilters import slugify
# Create your models here.
User = get_user_model()

class BlogPost(models.Model):
    title = models.CharField(max_length=255, unique=True, verbose_name="Titre")
    slug = models.SlugField(max_length=255, unique=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    last_updated = models.DateTimeField(auto_now=True)
    created_on = models.DateField(blank=True, null=True)
    published = models.BooleanField(default=False, verbose_name="Publié")
    content = models.TextField(blank=True, verbose_name="Contenu") 
    image = models.CharField(max_length=255, unique=True, null=True, verbose_name="Image")
    
    @property
    def author_or_default(self):
        return self.author.username if self.author else "L'auteur inconnu"
    def get_absolute_url(self): 
        return reverse("posts:home")

    class Meta:
        ordering = ['-created_on']
        verbose_name = "Article"

def __str__(self):
    return self.title
    
def save(self, args, **kwargs):
    if not self.slug:
        self.slug = slugify(self.title)
    super().save(args, **kwargs)

DocBlog/views.py
from datetime import datetime
from django.http import HttpResponse
from django.shortcuts import render

def index(request):
    date = datetime.today()
    return render(request,"DocBlog/index.html", context = {"date": date})

blog/views.py
from datetime import datetime
from django.http import HttpResponse
from django.shortcuts import render

def index(request):
    return render(request, "blog/index.html")

def blog(request, numero_blog):
    if numero_blog in ["01", "02", "03"]:
        return render(request, f"blog/blog_{numero_blog}.html", context={})
    return render(request, "blog/blog_not_found.html")

posts/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView,CreateView,UpdateView, DetailView, DeleteView
from posts.models import BlogPost

def index(request):
    return render(request, "posts/base.html")

class BlogHome(ListView):
    model = BlogPost
    context_object_name = "posts"

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.request.user.is_authenticated:
            return queryset
        return queryset.filter(published=True)

class BlogPostCreate(CreateView):
    model = BlogPost
    template_name = 'posts/blogpost_create.html'
    fields = ['title', 'content', 'slug', 'image', 'published' ]

class BlogPostEdit(UpdateView):
    model = BlogPost
    template_name = 'posts/blogpost_edit.html'
    fields = ['title', 'content', 'slug', 'image' ,'published' ]

class BlogPostDetail(DetailView):
    model = BlogPost
    context_object_name = "post"

class BlogPostDelete(DeleteView):
    model = BlogPost
    success_url = reverse_lazy("posts:home")

DocBlog/templates/DocBlog/carousel.html
<div id="carouselBasicExample" class="carousel slide carousel-fade" data-mdb-ride="carousel">
    <!-- Indicators -->
    <div class="carousel-indicators">
      <button
        type="button"
        data-mdb-target="#carouselBasicExample"
        data-mdb-slide-to="0"
        class="active"
        aria-current="true"
        aria-label="Slide 1"
      ></button>
      <button
        type="button"
        data-mdb-target="#carouselBasicExample"
        data-mdb-slide-to="1"
        aria-label="Slide 2"
      ></button>
      <button
        type="button"
        data-mdb-target="#carouselBasicExample"
        data-mdb-slide-to="2"
        aria-label="Slide 3"
      ></button>
    </div>
  
    <!-- Inner -->
    <div class="carousel-inner">
      <!-- Single item -->
      <div class="carousel-item active">
        <img src="https://mdbcdn.b-cdn.net/img/Photos/Slides/img%20(15).webp" class="d-block w-100" alt="Sunset Over the City"/>
        <div class="carousel-caption d-none d-md-block">
          <h5>First slide label</h5>
          <p>Nulla vitae elit libero, a pharetra augue mollis interdum.</p>
        </div>
      </div>
  
      <!-- Single item -->
      <div class="carousel-item">
        <img src="https://mdbcdn.b-cdn.net/img/Photos/Slides/img%20(22).webp" class="d-block w-100" alt="Canyon at Nigh"/>
        <div class="carousel-caption d-none d-md-block">
          <h5>Second slide label</h5>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
        </div>
      </div>
  
      <!-- Single item -->
      <div class="carousel-item">
        <img src="https://mdbcdn.b-cdn.net/img/Photos/Slides/img%20(23).webp" class="d-block w-100" alt="Cliff Above a Stormy Sea"/>
        <div class="carousel-caption d-none d-md-block">
          <h5>Third slide label</h5>
          <p>Praesent commodo cursus magna, vel scelerisque nisl consectetur.</p>
        </div>
      </div>
    </div>
    <!-- Inner -->
  
    <!-- Controls -->
    <button class="carousel-control-prev" type="button" data-mdb-target="#carouselBasicExample" data-mdb-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-mdb-target="#carouselBasicExample" data-mdb-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>

DocBlog/templates/DocBlog/contenue.html
<div class="container mb-5 mt-5">
    <div class="row">
        <div class="col-6 mt-5 mb-5 p-5">
            <img class="img-fluid" src="https://mdbcdn.b-cdn.net/img/new/standard/city/041.webp" />
        </div>
        <div class="col-6 align-self-center text-center">
            Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quaerat magni
            corrupti quae optio totam nostrum, fuga illum nihil itaque ad aperiam
            accusantium nemo et voluptatibus qui delectus maxime commodi? Velit.
        </div>
    </div>
    <div class="row">
        <div class="col-6 align-self-center text-align-right mt-5 mb-5 p-5 text-center">
            Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quaerat magni
            corrupti quae optio totam nostrum, fuga illum nihil itaque ad aperiam
            accusantium nemo et voluptatibus qui delectus maxime commodi? Velit.
        </div>
        <div class="col-6">
            <img class="img-fluid" src="https://mdbcdn.b-cdn.net/img/new/standard/city/041.webp" />
        </div>
    </div>
</div>

DocBlog/templates/DocBlog/footer.html
<!-- Footer -->
<footer class="bg-dark text-center text-white">
    <!-- Grid container -->
    <div class="container p-4">
      <!-- Section: Social media -->
      <section class="mb-4">
        <!-- Facebook -->
        <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
          ><i class="fab fa-facebook-f"></i
        ></a>
  
        <!-- Twitter -->
        <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
          ><i class="fab fa-twitter"></i
        ></a>
  
        <!-- Google -->
        <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
          ><i class="fab fa-google"></i
        ></a>
  
        <!-- Instagram -->
        <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
          ><i class="fab fa-instagram"></i
        ></a>
  
        <!-- Linkedin -->
        <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
          ><i class="fab fa-linkedin-in"></i
        ></a>
  
        <!-- Github -->
        <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
          ><i class="fab fa-github"></i
        ></a>
      </section>
      <!-- Section: Social media -->
  
      <!-- Section: Form -->
      <section class="">
        <form action="">
          <!--Grid row-->
          <div class="row d-flex justify-content-center">
            <!--Grid column-->
            <div class="col-auto">
              <p class="pt-2">
                <strong>Sign up for our newsletter</strong>
              </p>
            </div>
            <!--Grid column-->
  
            <!--Grid column-->
            <div class="col-md-5 col-12">
              <!-- Email input -->
              <div class="form-outline form-white mb-4">
                <input type="email" id="form5Example21" class="form-control" />
                <label class="form-label" for="form5Example21">Email address</label>
              </div>
            </div>
            <!--Grid column-->
  
            <!--Grid column-->
            <div class="col-auto">
              <!-- Submit button -->
              <button type="submit" class="btn btn-outline-light mb-4">
                Subscribe
              </button>
            </div>
            <!--Grid column-->
          </div>
          <!--Grid row-->
        </form>
      </section>
      <!-- Section: Form -->
  
      <!-- Section: Text -->
      <section class="mb-4">
        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt distinctio earum
          repellat quaerat voluptatibus placeat nam, commodi optio pariatur est quia magnam
          eum harum corrupti dicta, aliquam sequi voluptate quas.
        </p>
      </section>
      <!-- Section: Text -->
  
      <!-- Section: Links -->
      <section class="">
        <!--Grid row-->
        <div class="row">
          <!--Grid column-->
          <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
            <h5 class="text-uppercase">Links</h5>
  
            <ul class="list-unstyled mb-0">
              <li>
                <a href="#!" class="text-white">Link 1</a>
              </li>
              <li>
                <a href="#!" class="text-white">Link 2</a>
              </li>
              <li>
                <a href="#!" class="text-white">Link 3</a>
              </li>
              <li>
                <a href="#!" class="text-white">Link 4</a>
              </li>
            </ul>
          </div>
          <!--Grid column-->
  
          <!--Grid column-->
          <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
            <h5 class="text-uppercase">Links</h5>
  
            <ul class="list-unstyled mb-0">
              <li>
                <a href="#!" class="text-white">Link 1</a>
              </li>
              <li>
                <a href="#!" class="text-white">Link 2</a>
              </li>
              <li>
                <a href="#!" class="text-white">Link 3</a>
              </li>
              <li>
                <a href="#!" class="text-white">Link 4</a>
              </li>
            </ul>
          </div>
          <!--Grid column-->
  
          <!--Grid column-->
          <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
            <h5 class="text-uppercase">Links</h5>
  
            <ul class="list-unstyled mb-0">
              <li>
                <a href="#!" class="text-white">Link 1</a>
              </li>
              <li>
                <a href="#!" class="text-white">Link 2</a>
              </li>
              <li>
                <a href="#!" class="text-white">Link 3</a>
              </li>
              <li>
                <a href="#!" class="text-white">Link 4</a>
              </li>
            </ul>
          </div>
          <!--Grid column-->
  
          <!--Grid column-->
          <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
            <h5 class="text-uppercase">Links</h5>
  
            <ul class="list-unstyled mb-0">
              <li>
                <a href="#!" class="text-white">Link 1</a>
              </li>
              <li>
                <a href="#!" class="text-white">Link 2</a>
              </li>
              <li>
                <a href="#!" class="text-white">Link 3</a>
              </li>
              <li>
                <a href="#!" class="text-white">Link 4</a>
              </li>
            </ul>
          </div>
          <!--Grid column-->
        </div>
        <!--Grid row-->
      </section>
      <!-- Section: Links -->
    </div>
    <!-- Grid container -->
  
    <!-- Copyright -->
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
      © 2020 Copyright:
      <a class="text-white" href="https://mdbootstrap.com/">MDBootstrap.com</a>
    </div>
    <!-- Copyright -->
  </footer>
  <!-- Footer -->

DocBlog/templates/DocBlog/index.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static '/style.css' %}" />
  <meta charset="UTF-8" />
  <title>Mon blog</title>
</head>

<body>
{% include 'DocBlog/navbar.html' %}
{% include 'DocBlog/carousel.html' %}
{% include 'DocBlog/contenue.html' %}
{% include 'DocBlog/footer.html' %}
</body>

</html>

DocBlog/templates/DocBlog/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <!-- Container wrapper -->
    <div class="container-fluid">
      <!-- Toggle button -->
      <button class="navbar-toggler" type="button" data-mdb-toggle="collapse" data-mdb-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <i class="fas fa-bars"></i>
      </button>

      <!-- Collapsible wrapper -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <!-- Navbar brand -->
        <a class="navbar-brand mt-2 mt-lg-0" href="#">
          <img src="https://mdbcdn.b-cdn.net/img/logo/mdb-transaprent-noshadows.webp" height="15" alt="MDB Logo"
            loading="lazy" />
        </a>
        <!-- Left links -->
        <ul class="navbar-nav mx-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" href="#">Accueil</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Notre Histoire</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Notre Equipe</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="posts">Blog</a>
          </li>
        </ul>
        <!-- Left links -->
      </div>
      <!-- Collapsible wrapper -->

      <!-- Right elements -->
      <div class="d-flex align-items-center">
        <!-- Icon -->
        <a class="text-reset me-3" href="#">
          <i class="fas fa-shopping-cart"></i>
        </a>

        <!-- Notifications -->
        <div class="dropdown">
          <a class="text-reset me-3 hidden-arrow" href="#" id="navbarDropdownMenuLink" role="button"
            data-mdb-toggle="dropdown" aria-expanded="false">
            <i class="fas fa-bell"></i>
          </a>
          <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownMenuLink">
            <li>
              <a class="dropdown-item" href="#">Some news</a>
            </li>
            <li>
              <a class="dropdown-item" href="#">Another news</a>
            </li>
            <li>
              <a class="dropdown-item" href="#">Something else here</a>
            </li>
          </ul>
        </div>
        <!-- Avatar -->
        <div class="dropdown">
          <a class="d-flex align-items-center hidden-arrow" href="#" id="navbarDropdownMenuAvatar"
            role="button" data-mdb-toggle="dropdown" aria-expanded="false">
            <img src="https://mdbcdn.b-cdn.net/img/new/avatars/2.webp" class="rounded-circle" height="25"
              alt="Black and White Portrait of a Man" loading="lazy" />
          </a>
          <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownMenuAvatar">
            <li>
              <a class="dropdown-item" href="#">My profile</a>
            </li>
            <li>
              <a class="dropdown-item" href="#">Settings</a>
            </li>
            <li>
              <a class="dropdown-item" href="#">Logout</a>
            </li>
          </ul>
        </div>
      </div>
      <!-- Right elements -->
    </div>
    <!-- Container wrapper -->
  </nav>

DocBlog/templates/blog/blog_01.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Article 1</title>
  </head>
  <body>
    <h1>Article n°1</h1>
  </body>
</html>

DocBlog/templates/blog/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Mon blog</title>
  </head>
  <body>
    <h1>Le blog</h1>
  </body>
</html>

DocBlog/templates/posts/base.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    {% block title %}{% endblock %}
    
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static '/style.css' %}" />
</head>
<body>

{% include 'posts/navbar.html' %}
<section class="mt-5 mb-5" id="blog">
    {% block content %}
    {% endblock %}
</section>
{% include 'DocBlog/footer.html' %}

</body>
</html>

DocBlog/templates/posts/blogpost_confirm_delete.html
{% extends 'posts/base.html' %}
{% block content %}
    <form method="POST">
        {% csrf_token %}
        <p>Êtes-vous sûr de vouloir supprimer "{{ object }}"?</p>
        <input type="submit" value="Oui, supprimer">
    </form>
{% endblock %}

DocBlog/templates/posts/blogpost_create.html
{% extends 'posts/base.html' %}
{% block title %}
    <title>Ajouter un article</title>
{% endblock %}
{% block content %}
<div class="container">
    <h1>Ajouter un article</h1>
    <form method="POST">
        {% csrf_token %}
        
        <div  class="d-flex flex-column">
        {{ form }}
        </div>
        <input class="btn btn-success" type="submit" value="Créer">
    </form>
</div>
{% endblock %}

DocBlog/templates/posts/blogpost_detail.html
{% extends 'posts/base.html' %}
{% block title %}
    <title>{{ post.title }}</title>
{% endblock %}
{% block content %}
    <article class="container">
        <img class="img-fluid" height="300" src={{ post.image }} >
        <div class="p-5">
        <h1>{{ post.title }}</h1>
        <div>{{ post.content|linebreaks|safe }}</div>
    </div>
    </article>
{% endblock %}

DocBlog/templates/posts/blogpost_edit.html
{% extends 'posts/base.html' %}
{% block title %}
    <title>Éditer l'article</title>
{% endblock %}
{% block content %}
<div class="container">
<h1>Éditer l'article</h1>
    <form method="POST">
        {% csrf_token %}
        <div  class="d-flex flex-column">
        {{ form }}
    </div>
        <div class="text-center">
        <input class="btn btn-primary mx-auto" type="submit" value="Éditer">
    </div>
    </form>
</div>
{% endblock %}

DocBlog/templates/posts/blogpost_list.html
{% extends 'posts/base.html' %} {% block content %}
<div class="container">
    <div class="d-flex justify-content-between mt-5">
        <h1>La caserne d'Eddy</h1>

        {% if request.user.is_authenticated %}
        <a href="{% url 'posts:create' %}"><button class="btn btn-primary">Ajouter un article</button></a>
        {% endif %}
    </div>
    <div class="row">
        {% for post in posts %}
        <div class="col-lg-4">
            <article>
                <div class="card">
                    <img src={{post.image}} class="card-img-top" height="300" alt="Fissure in Sandstone" />
                    <div class="card-body">
                        <h5 class="card-title">{{ post.title }}</h5>
                        <p class="card-text text-truncate">{{ post.content|safe|truncatewords:50 }}</p>
                        {% if request.user.is_authenticated %}
                        <a href="{% url 'posts:edit' slug=post.slug %}" class="btn btn-primary">
                            Éditer
                        </a>
                        <a href="{% url 'posts:delete' slug=post.slug %}" class="btn btn-danger">
                            Supprimer
                        </a>
                        {% endif %}
                    </div>
                </div>

                <span>
                    Publié par
                    <i>{{ post.author_or_default }}</i>
                    le {{ post.created_on|date:'j F Y' }}
                </span>

                <!-- Un beau bouton -->
                <form class="text-center" action="{% url 'posts:post' slug=post.slug %}">
                    <button class="btn btn-sm btn-secondary">Lire l'article</button>
                </form>
            </article>
        </div>

        {% endfor %}
    </div>
</div>
{% endblock %}

DocBlog/templates/posts/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <!-- Container wrapper -->
    <div class="container-fluid">
      <!-- Toggle button -->
      <button class="navbar-toggler" type="button" data-mdb-toggle="collapse" data-mdb-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <i class="fas fa-bars"></i>
      </button>

      <!-- Collapsible wrapper -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <!-- Navbar brand -->
        <a class="navbar-brand mt-2 mt-lg-0" href="#">
          <img src="https://mdbcdn.b-cdn.net/img/logo/mdb-transaprent-noshadows.webp" height="15" alt="MDB Logo"
            loading="lazy" />
        </a>
        <!-- Left links -->
        <ul class="navbar-nav mx-auto mb-2 mb-lg-0">
            <!-- On ajoute le menu à l'intérieur d'une balise nav -->
            
          <li class="nav-item">
            <a class="nav-link" href="{% url 'posts:home' %}">Accueil</a> 
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Notre Histoire</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Notre Equipe</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="posts">Blog</a>
          </li>
        </ul>
        <!-- Left links -->
      </div>
      <!-- Collapsible wrapper -->

      <!-- Right elements -->
      <div class="d-flex align-items-center">
        <!-- Icon -->
        <a class="text-reset me-3" href="#">
          <i class="fas fa-shopping-cart"></i>
        </a>

        <!-- Notifications -->
        <div class="dropdown">
          <a class="text-reset me-3 hidden-arrow" href="#" id="navbarDropdownMenuLink" role="button"
            data-mdb-toggle="dropdown" aria-expanded="false">
            <i class="fas fa-bell"></i>
          </a>
          <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownMenuLink">
            <li>
              <a class="dropdown-item" href="#">Some news</a>
            </li>
            <li>
              <a class="dropdown-item" href="#">Another news</a>
            </li>
            <li>
              <a class="dropdown-item" href="#">Something else here</a>
            </li>
          </ul>
        </div>
        <!-- Avatar -->
        <div class="dropdown">
          <a class="d-flex align-items-center hidden-arrow" href="/admin" id="navbarDropdownMenuAvatar"
            role="button" data-mdb-toggle="dropdown" aria-expanded="false">
            <img src="https://mdbcdn.b-cdn.net/img/new/avatars/2.webp" class="rounded-circle" height="25"
              alt="Black and White Portrait of a Man" loading="lazy" />
          </a>
          <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownMenuAvatar">
            <li>
              <a class="dropdown-item" href="#">My profile</a>
            </li>
            <li>
              <a class="dropdown-item" href="#">Settings</a>
            </li>
            <li>
              <a class="dropdown-item" href="#">Logout</a>
            </li>
          </ul>
        </div>
      </div>
      <!-- Right elements -->
    </div>
    <!-- Container wrapper -->
  </nav>